src/base/ApplicationAutoscaling.ts, src/base/__snapshots__/ApplicationAutoscaling.spec.ts.snap, src/pocket/__snapshots__/PocketALBAppliation.spec.ts.snap
Fix alarm dimensions to respect case. This is related to CDK bug hashicorp/terraform-cdk#235
=> fix(alarms): Fix alarm dimensions to respect case

src/pocket/PocketPagerDuty.spec.ts, src/pocket/PocketPagerDuty.ts, src/pocket/__snapshots__/PocketPagerDuty.spec.ts.snap
Create a Pocket Pagerduty construct
=> fix(pagerduty): Add Pocket PagerDuty module

src/pocket/PocketEventBridgeWithLambdaTarget.spec.ts, src/pocket/PocketEventBridgeWithLambdaTarget.ts, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap
Add configurable alarm option to lambda alarms
=> fix(lambda-alarms): Add treatMissingData option

src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationVersionedLambda.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketSQSWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketVersionedLambda.spec.ts.snap
Allow us to run lambdas leveraging this class to be executed at CloudFront edge.
=> Allow lambdas to be executed at edge

src/base/ApplicationElasticacheCluster.spec.ts, src/base/ApplicationElasticacheCluster.ts, src/base/__snapshots__/ApplicationElasticacheCluster.spec.ts.snap, src/index.ts
Create a module that does a default elasticache setup
=> feat(elasticache): adding in elasticache module

src/base/ApplicationElasticacheCluster.ts
Fix the typo I made in elasticache cluster
=> fix(typo): fixing typo in elasticache cluster

.eslintrc.js, .github/dependabot.yml, package-lock.json, package.json
=> chore(dependencies): update dependencies

src/base/ApplicationECSContainerDefinition.ts
Add `dependsOn` as an option container definition property
=> fix(container definition): add 'dependsOn' as an optional prop

package-lock.json, package.json
=> fix(dependencies): upgrade dependencies

src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts
Expose the ECS service object from PocketALBApplication
=> feat(pocket alb application): Expose the ECS service

src/base/ApplicationAutoscaling.spec.ts, src/base/ApplicationAutoscaling.ts, src/base/ApplicationBaseDNS.spec.ts, src/base/ApplicationBaseDNS.ts, src/base/ApplicationCertificate.spec.ts, src/base/ApplicationCertificate.ts, src/base/__snapshots__/ApplicationBaseDNS.spec.ts.snap, src/base/__snapshots__/ApplicationCertificate.spec.ts.snap
improve modularity on a couple more base modules:
- ApplicationBaseDNS
- ApplicationCertificate
did some renaming in `ApplicationAutoscaling` for clarity between vars and types.
=> refactor(base modules) - improve modularity on a couple more objects

src/utilities.jest.ts
Fixed typo in test name, does not change any functionality.
=> test(utilities): Fixed typo in test name

.gitignore, tsconfig.json
This improves the compile / synth time on recompile by 1-2s out of 15s
Omit this section if not applicable.
Have you followed the guidelines in our Contributing document?
* Link to docs
Tickets:
* Link to JIRA tickets
=> chore(perf): enable incremental build for faster rebuild times

.github/workflows/verified_commits_check.yml
To alert contributors early if their commit is unsigned. Using https://github.com/Nadock/verified_commits_check.
=> chore(actions): Add verified commits check

.circleci/config.yml, package.json
Please review #383 for all updates
BREAKING CHANGE: Please note that CDK for Terraform 0.7 contains breaking changes that will require code updates for namespacing AWS provider resources
=> feat(cdktf): Bump cdktf to version 0.7

.gitignore, README.md, package-lock.json, src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationVersionedLambda.spec.ts.snap, src/pocket/PocketApiGatewayLambdaIntegration.spec.ts, src/pocket/PocketApiGatewayLambdaIntegration.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketSQSWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketVersionedLambda.spec.ts.snap
Create an API Gateway construct with lambda proxy integrations, for Pocket. Only minimal configuration options at this time, for our use case -- more can be added later in a backwards-compatible fashion.
The below configuration creates an API Gateway with an endpoint named `/endpoint` that accepts POST requests and forwards them to the appropriate lambda. 
```
class Example extends TerraformStack {
constructor(scope: Construct, name: string) {
super(scope, name);
new AwsProvider(this, 'aws', {
region: 'us-east-1',
});
new LocalProvider(this, 'local', {});
new NullProvider(this, 'null', {});
new ArchiveProvider(this, 'archive', {});
const config: PocketApiGatewayProps = {
name: 'test-api-lambda',
stage: 'test',
routes: [
{
path: 'endpoint',
method: 'POST',
eventHandler: {
name: …
```
=> feat(api gateway): Pocket api gateway construct with lambda proxy integrations

src/base/ApplicationCertificate.ts, src/example.ts, src/pocket/PocketApiGatewayLambdaIntegration.spec.ts, src/pocket/PocketApiGatewayLambdaIntegration.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap
- setup route 53 for api gateway
Ticket: https://getpocket.atlassian.net/browse/INFRA-192
=> feat(api-gateway): adding route53 to pocket api gateway construct. 

src/base/ApplicationECSContainerDefinition.spec.ts, src/base/ApplicationECSContainerDefinition.ts
An additional configurable item needed for getting the kinesis-agent running for https://github.com/Pocket/Parser/pull/255#pullrequestreview-846224828
=> feat(ApplicationEcsContainerDefinition): Add ability to pass boolean to essential

src/index.ts
Now ready to export this class so that we can use in a downstream project.
The continuation of https://github.com/Pocket/terraform-modules/pull/484
=> chore(PocketSynthetics): Export so we can use PocketSynthetics

src/pocket/PocketSynthetics.ts, src/pocket/__snapshots__/PocketSynthetics.spec.ts.snap
This will automatically close alerts in PagerDuty
=> feat(PocketSynthetics): Set fill value and fill option 

.github/linters/.eslintrc.js, .github/workflows/linter.yml
Linter broke on yaml files so lets disable it.
=> chore(linter): fixing the yaml linter

src/base/ApplicationECSIAM.ts, src/base/ApplicationECSService.ts, src/index.ts
Expose ECS IAM role from the ApplicationECSService construct
=> fix(ECS IAM): Expose ECS IAM role from the ApplicationECSService construct

package-lock.json, package.json
Fixing a forgotten removal in https://github.com/Pocket/terraform-modules/pull/890
=> build(npm): removing registry config

src/base/ApplicationLambdaSnsTopicSubscription.spec.ts, src/base/ApplicationLambdaSnsTopicSubscription.ts, src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationLambdaSnsTopicSubscription.spec.ts.snap
Add a Lambda subscription on an SNS Topic. Creates a subscription on an existing SNS topic to invoke a Lambda function. Automatically configures permissions for Lambda and creates a DLQ for messages that failed to be sent to the Lambda.
**Changes**
* Expose the base Lambda on PocketVersionedLambda class (SNS needs to invoke the base lambda and have permissions configured that way, not the alias)
* Add the `ApplicationLambdaSnsTopicSubscription` class
Relates to [INFRA-654]
Dev test example:
```
import { Construct } from 'constructs';
import { App, TerraformStack } from 'cdktf';
import { AwsProvider, sns } from '@cdktf/provider-aws';
import { LocalProvider } from '@cdktf/provider-local';
import { NullProvider } from '@cdktf/provider-null';
import { ArchiveProvider } from …
```
=> feat: Lambda subscription on SNS topic

src/index.ts
Expose ApplicationLambdaSnsTopicSubscription
=> fix: export ApplicationLambdaSnsTopicSubscription

src/base/ApplicationEventBridgeRule.spec.ts, src/base/ApplicationEventBridgeRule.ts, src/base/__snapshots__/ApplicationEventBridgeRule.spec.ts.snap
Expose `scheduleExpression` for ApplicationEventBridgeRule
Tickets:
* Pre-requesite for [INFRA-690]
[INFRA-690]: https://getpocket.atlassian.net/browse/INFRA-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ApplicationEventBridgeRule): expose scheduleExpression

src/base/ApplicationECSAlbCodeDeploy.ts, src/base/ApplicationLambdaCodeDeploy.ts, src/base/__snapshots__/ApplicationECSAlbCodeDeploy.spec.ts.snap, src/base/__snapshots__/ApplicationLambdaCodeDeploy.spec.ts.snap, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap, src/pocket/__snapshots__/PocketVersionedLambda.spec.ts.snap
additional principal identifiers needing 'codedeploy.' prepended
Tickets:
* [POC-189](https://mozilla-hub.atlassian.net/browse/POC-189)
=> fix: additional principal identifiers needing 'codedeploy.' prepended

README.md, src/base/ApplicationECSContainerDefinition.ts, src/base/ApplicationECSService.ts, src/example.ts
Make logstream prefixes configurable.
=> feat(logstream): have ECS log stream prefix be configurable

README.md, package-lock.json, src/pocket/PocketCloudwatchSynthetics.spec.ts, src/pocket/PocketCloudwatchSynthetics.ts, src/pocket/__snapshots__/PocketCloudwatchSynthetics.spec.ts.snap
Adding optional `userId` param to `PocketCloudWatchSynthetics`
Tickets:
* [https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-386](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-386)
=> SOCIALPLAT-386: adding userId to PocketCloudWatchSynthetics

src/pocket/PocketCloudwatchSynthetics.spec.ts, src/pocket/PocketCloudwatchSynthetics.ts, src/pocket/__snapshots__/PocketCloudwatchSynthetics.spec.ts.snap
Adding optional `userId` to CloudWatchSynthetics.
Tickets:
* [https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-386](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-386)
=> feat(synchecks): adding userId to CloudWatchSynthetics

src/base/ApplicationECSContainerDefinition.ts
Add in a stop timeout that can be used to let a container gracefully exit.
=> fix(stopTimeout): adding in stop timeout options
