src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
- Validate alarm config to check `datapointsToAlarm` is not greater than `evaluationPeriods`.
- Add tests for alarm config validation.
- Fix alarm names to avoid double prefixing.
=> fix(alarms): Validate alarm config and fix name prefix

src/base/ApplicationAutoscaling.ts, src/pocket/PocketALBApplication.ts, src/pocket/PocketEventBridgeWithLambdaTarget.spec.ts, src/pocket/PocketEventBridgeWithLambdaTarget.ts, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap
- Add alarms support to PocketEventBridgeWithLambdaTarget module
- Stop using escape hatch for dimensions in other modules (fixed in `cdktf` 0.0.19)
=> fix(lambda-alarms): Add alarms support to PocketEventBridgeWithLambdaTarget module

src/base/ApplicationECSContainerDefinition.spec.ts, src/base/ApplicationECSContainerDefinition.ts
Add `healthCheck` property to `containerConfigs`.
If no container health check is set, blue/green deployments will succeed whenever tasks get to the 'running' state, regardless of whether a target group health check will subsequently stop the tasks. This means a deployment may succeed and bring down the service.
Tickets:
* https://getpocket.atlassian.net/browse/BACK-625
- Is there a reason why we're manually stringifying json? Why ``'[' + config.command.map((c) => `"${c}"`).join(',') + ']'`` instead of `JSON.stringify(config.command)`? The latter also json-escapes values, which would matter for a command like `curl -f "http://127.0.0.1:8000/pulse" || exit 1`.
- The health check is not set by default using the `exposedContainer` property in `PocketALBApplication`, because we can't know …
=> feat(ecs) Add container health check property

src/base/ApplicationVersionedLambda.spec.ts, src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationVersionedLambda.spec.ts.snap
Support node v14 Lambda runtime, which has [long-term support](https://nodejs.org/en/about/releases/) until 2023-04-30. Node v12 is supported until 2022-04-30.
- [List of Lambda runtimes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime)
=> feat(lambda): Add NODEJS14 Lambda runtime

src/pocket/PocketSQSWithLambdaTarget.spec.ts, src/pocket/PocketSQSWithLambdaTarget.ts, src/pocket/__snapshots__/PocketSQSWithLambdaTarget.spec.ts.snap
Allow PocketSQSWithLambdaTarget to accept an existing SQS queue, instead of creating one.
This is necessary for the Parser cron job migration.
- I tried writing two interfaces that [enforce the either-or constraint through typing](https://stackoverflow.com/a/61281828/331030). This ended up feeling cluttered.
- We could create two classes, for new and existing SQS queues respectively, and put the shared logic in an abstract class. This seems like it might get cluttered too, and would deviate from the existing patterns.
Tickets:
* https://getpocket.atlassian.net/browse/BACK-704
Parser migration:
* https://docs.google.com/document/d/1O6HArmwD1QdKP92-yJwzny7XI_mD-LLiqQ3tG6b-dnA/edit#
=> feat(lambda): trigger Lambda using an existing SQS queue

src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts
Expose the ALB listeners to allow consumers to update outside of the module. Ex. adding extra SSL certificates(this is the current use case for this change).
=> feat(pocket alb application): Expose ALB listeners

src/base/ApplicationECSAlbCodeDeploy.ts, src/base/ApplicationECSService.ts, src/example.ts, src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
By default, traffic is redirected to https. Allow implementing services to choose to send http traffic directly to the target.
Some legacy clients do not support redirects, and make requests on port 80. This change allows us to keep supporting them, until they are migrated to https.
* [AWS tutorial for test listeners](https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorial-ecs-deployment-with-hooks.html)
Tickets:
* https://getpocket.atlassian.net/browse/BACK-781
- It feels a bit ugly to have a `disableHttpsForwarding` parameter at all. Would it be good to deprecate it, as a signal that it preferably shouldn't be enabled, and that this is intended to be used temporarily?
- Not exposing testListener through `PocketALBApplication` yet because there hasn't been a …
=> feat(pocket alb application): Add option to disable HTTPS forwarding

src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
Fix a bug that applied the httpLatency actions to the HTTPRequestCount alarm.
There is some duplicate code between the three alarms, which is likely how this bug was introduced. It would be nice to make this code more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), but I'm considering it out-of-scope for this fix.
=> fix(pocket alb application): Apply httpRequestCount actions correctly

src/base/ApplicationECSService.spec.ts, src/base/ApplicationECSService.ts, src/base/__snapshots__/ApplicationECSService.spec.ts.snap, src/index.ts, src/pocket/PocketECSCodePipeline.spec.ts, src/pocket/PocketECSCodePipeline.ts, src/pocket/__snapshots__/PocketECSCodePipeline.spec.ts.snap
Create a CodePipeline to queue code deployments.
=> feat(pocket-ecs-codepipeline): Add a Pocket ECS CodePipeline module

cdktf.json, src/base/ApplicationECSService.ts, src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
Create `appspec.json` and `taskdef.json` when an alb configuration is provided
- Generate `appspec.json`
- Generate `taskdef.json`
- Add config option `useCodePipeline` on PocketALBApplication to be used when creating the ECS application
=> feat(codepipeline): Generate appspec.json and taskdef.json on terrform apply

src/base/ApplicationDynamoDBTable.spec.ts, src/base/ApplicationDynamoDBTable.ts, src/base/__snapshots__/ApplicationDynamoDBTable.spec.ts.snap
Prevent DynamoDB tables from being destroyed accidentally, for example by changing the primary key. 
- Tables are protected by default.
- Set 'preventDestroyTable' to `false` to disable this protection.
This was requested for our recommendation metrics tables. There haven't been any incidents yet were tables were accidentally removed; this is purely preventative.
Successfully tested in our development environment:
```
Error: Instance cannot be destroyed
on cdk.tf.json line 25, in resource.aws_dynamodb_table:
25:       "acmeexample_recommendationmetrics_dynamodbtable_3402FAB3": {
Resource
aws_dynamodb_table.acmeexample_recommendationmetrics_dynamodbtable_3402FAB3
has lifecycle.prevent_destroy set, but the plan calls for this resource to be
destroyed. To avoid this error and continue with …
```
=> feat(dynamodb): Protect DynamoDB tables from being destroyed

src/base/ApplicationAutoscaling.spec.ts, src/base/ApplicationAutoscaling.ts, src/base/__snapshots__/ApplicationAutoscaling.spec.ts.snap, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap, src/testHelpers.ts
move logic to static functions.
- move code out of constructor into static functions
- make code a bit more DRY
- add tests for all static functions
- add a test helper for an empty/blank construct
attempting to make the code more modular and easier to test in pieces. if we like this pattern (and we don't have to), i'll continue into the rest of the components.
=> refactor(ApplicationAutoscaling) - move logic to static functions

.github/workflows/publish_github.yml, .github/workflows/publish_npm.yml
Publish terraform-modules to the public NPM repository [pocket-tools](https://www.npmjs.com/settings/pocket-tools/packages).
pocket-tools on NPM:
* https://www.npmjs.com/settings/pocket-tools/packages
- Support users who currently pull this package from Github by pushing to both repositories. We duplicate YML file to achieve this.
=> feat(NPM): Publish terraform-modules to NPM

.github/workflows/pre_publish.yml, .github/workflows/publish.yml
Based on the response from GitHub in https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544 let's separate our workflows to allow the main branch to access secrets when a dependabot auto merge has occurred.
=> chore(release): updating flows to use triggers

src/base/ApplicationDynamoDBTable.spec.ts, src/base/ApplicationDynamoDBTable.ts, src/base/__snapshots__/ApplicationDynamoDBTable.spec.ts.snap
Add an option to ApplicationDynamoDBTable set the capacity mode to [on-demand](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html). The default will remain provisioned capacity.
See Implementation Decisions below.
* https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html
Tickets:
* https://getpocket.atlassian.net/browse/HOMPER-42
- AWS is inconsistent about how it calls 'on-demand' capacity. In the AWS Console and in documentation the capacity mode is called 'on-demand', but in CloudFormation (which Terraform is based on) it is called 'PAY_PER_REQUEST'. Additionally 'capacity mode' is called 'billing mode'. I'd like the Terraform-Modules interface to use the more readable …
=> Dynamodb on demand mode

src/base/ApplicationRDSCluster.spec.ts, src/base/ApplicationRDSCluster.ts, src/base/__snapshots__/ApplicationRDSCluster.spec.ts.snap
Have the package generate the value for database URL in RDS secrets. Since I'm not sure what the connection URL is for `aurora` and `aurora-postgresql` engines, I'm only setting it if the engine is `aurora-mysql` so as not to affect anything else downstream. Would love to be able to implement it for all engine types though.
- Add a database URL for MySQL-compatible Aurora instances.
- Fix typos in comments.
=> feat(rds): Add an optional database URL to RDS secret

src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
- When default alarms `httpLatency` and `http5xxError` properties are not defined, skip creating any alarms.
- Remove `httpRequestCount` alarm, if needed, it can be added as a custom alarm
- Rename `http5xxError` to `http5xxErrorPercentage`
Tickets: 
- BACK-1068
- BACK-1054
=> feat(alarms): remove request count alarm and make default alarms optional

src/pocket/PocketALBApplication.ts
Use target 5xx count to determine the 5xx error rate
=> fix(error rate alarm): Use the target 5xx errors instead of the elb

src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationVersionedLambda.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketSQSWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketVersionedLambda.spec.ts.snap
Get the function version correctly from the function's qualified arn instead of the FQN to avoid a validation error
Qualified ARN format example: `arn:aws:lambda:aws-region:acct-id:function:helloworld:42` ([Source](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html#versioning-versions-using))
=> fix(lambda): Fix Lambda alias function version

src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
As part of my ongoing PagerDuty work I would like to modify our default alarms to allow changing the description. The intention here is to add a link in the description to a runbook or troubleshooting for the alarm.
For example for a `5xx` error on the `Parser` I'd imagine linking to a runbook in our Confluence that has some common troubleshooting steps for what to do when you get that alert for `5xx`.
* [ JIRA](https://mozilla-hub.atlassian.net/browse/SE-2875)
=> feat(Allow configuring Alarm Description)

src/index.ts
Export the typescript class and types for PocketApiGatewayLambdaIntegration
=> fix(types): Export the PocketApiGatewayLambdaIntegration class and types

package-lock.json, package.json, src/example.ts, src/pocket/PocketApiGatewayLambdaIntegration.spec.ts, src/pocket/PocketApiGatewayLambdaIntegration.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap
- JSON encode the `PocketApiGatewayProps` to trigger redeployment of the API Gateway resource
- Add tags to the API Gateway REST API resource
- redeployment triggers are provided by the service consuming the API gateway construct. if no trigger is provided, then we use the current time as the trigger. this way, what's being set as a trigger becomes the responsibility of the consuming service
ticket:[ infra-188 ](https://getpocket.atlassian.net/browse/INFRA-188)
=> fix(api gateway lambda integration): Fix redeployment trigger

src/pocket/PocketApiGatewayLambdaIntegration.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap
add lifecycle property to api gateway
otherwise  code build throws an error: 
`Error: error deleting API Gateway Deployment (ixfyda): BadRequestException: Active stages pointing to this deployment must be moved or deleted`
fix from this github issue: https://github.com/hashicorp/terraform/issues/10674
Tickets:
infra-188
=> fix(api-gateway): add lifecycle property to api gateway

src/base/ApplicationECSContainerDefinition.spec.ts, src/base/ApplicationECSContainerDefinition.ts
The pocket/parser repo uses this for creating it's container definition. I need to pass in entrypoint so that I can create the kinesis-agent config. 
Tickets:
* https://mozilla-hub.atlassian.net/browse/SE-2958
=> feat(ApplicationECSContainerDefinition) Allow passing entrypoint

src/pocket/PocketECSCodePipeline.spec.ts, src/pocket/PocketECSCodePipeline.ts, src/pocket/__snapshots__/PocketECSCodePipeline.spec.ts.snap
Allow CodePipeline steps to be added to `PocketECSCodePipeline`.
Our immediate use-case is that we want to add a deployment step that registers Prefect flows. The new test case illustrates how we might do this.
Changes:
- Add `preDeployStages` and `postDeployStages` properties to respectively run stages before and after the deployment.
- Change CodePipeline permissions to execute CodeBuild project if name starts with `prefix`, instead of requiring an exact match. This makes it easy to add custom CodeBuild actions.
- Extracted parts of `createCodePipeline` into smaller methods.
Related PR:
* https://github.com/Pocket/data-flows/pull/12
- Originally we made methods in this class `protected` to allow the CodePipeline stages to be customized. This allows for a lot of customization. After …
=> feat(pocket-ecs-codepipeline): Make codepipeline steps extendable

src/base/ApplicationECSService.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
This just bit me locally. I do not set a default region as I work with many regions and it can be dangerous to assume a default.
I noticed that `region` is actually optional so there may be other places we are making this assumption.
=> feat(region): Pass region into aws command, default to us-east-1

src/pocket/PocketSQSWithLambdaTarget.ts
Make `functionResponseTypes` configurable. Can use it to report individual failures when processing batches from e.g. SQS.
* [Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#function_response_types)
* [AWS Docs ](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html#services-ddb-batchfailurereporting)
=> feat(sqsLambda): make functionResponseTypes configurable

src/index.ts
Export the `PocketEventBridgeWithLambdaTarget` construct
=> fix(event bridge with multiple targets): export PocketEventBridgeWithLambdaTarget construct

src/base/ApplicationBackups.spec.ts, src/base/ApplicationBackups.ts, src/base/__snapshots__/ApplicationBackups.spec.ts.snap
Allow use of managed AWS Backups service
**To setup a sample backup you can use the following configuration:** 
```
import { Construct } from 'constructs';
import { App, TerraformStack } from 'cdktf';
import { AwsProvider } from '@cdktf/provider-aws';
import { ApplicationBackup } from './base/ApplicationBackups';
class Example extends TerraformStack {
constructor(scope: Construct, name: string) {
super(scope, name);
new AwsProvider(this, 'aws', {
region: '<region>',
});
new ApplicationBackup(this, '<vault_name>', {
name: 'Vault',
kmsKeyArn: 'arn:aws:kms:<region>::<key_name>',
prefix: '<prefix>',
accountId: '<account_id>',
vaultPolicy: '{"Version":"2012-10-17","Statement":[{"Sid":"Allowaccounttocopyintobackupvault","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::<backup_account_id>:<backu …
```
=> feat(aws/backups): aws backup integration

src/pocket/PocketSQSWithLambdaTarget.ts
Make `sqsQueueResource` a public property so that the underlying data (e.g. `arn`) can be accessed for additional permissions/integrations.
=> feat: expose sqsQueueResource on PocketSQSWithLambdaTarget

src/base/ApplicationSQSQueue.ts, src/pocket/PocketSQSWithLambdaTarget.ts
Expose the dead letter queue that may be created on the `ApplicationSQSQueue` construct.
Expose the `ApplicationSQSQueue` construct created as part of the `PocketSQSWithLambdaTarget` construct
=> fix(application sqs queue): expose dead letter queue

src/base/ApplicationEventBridgeRule.ts, src/base/ApplicationEventBus.spec.ts, src/base/ApplicationEventBus.ts, src/base/__snapshots__/ApplicationEventBridgeRule.spec.ts.snap, src/base/__snapshots__/ApplicationEventBus.spec.ts.snap, src/example.ts, src/pocket/__snapshots__/PocketEventBridgeRuleWithMultipleTargets.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap
- to create custom event bus for event-rules and their targets.
- created `ApplicationEventBus` for rolling out custom event bus
- if the `eventBus` is given in the event-rule props, then it is assigned to both event-rule and all its targets.
- if the custom event bus name is not given in the event-rule props, then the `default` event bus is assumed.
- we don't roll-out eventBus as a part of `PocketEventBridgeRuleWithMultipleTargets` construct. if the consuming application requires it, then it can create one and attach them to the pocket construct. 
```
Error: Creating EventBridge Target failed: ResourceNotFoundException: 
Rule test-event-bridge-rule-multiple-targets-Rule does not exist on EventBus default.
```
- fixed by assigning event bus name to the targets as well. 
[custom event …
=> feat(event-bus): add event bus application construct

src/base/ApplicationECSService.spec.ts, src/base/ApplicationECSService.ts
Expose the ECR repositories that may be created by the `ApplicationECSService`. The immediate need is that the DataFlows repo needs to reference this ECR repo. (See [FFRECSV2-217](https://getpocket.atlassian.net/browse/FFRECSV2-217) for more details.)
Tickets:
* https://getpocket.atlassian.net/browse/FFRECSV2-217
- I couldn't see how to unpack `this.setupECSTaskDefinition()` directly unto class fields, so I used a simple assignment.
=> Fix(application ecs service): expose ECR repos and task definition

src/base/ApplicationVersionedLambda.ts, src/base/__snapshots__/ApplicationVersionedLambda.spec.ts.snap, src/pocket/PocketVersionedLambda.spec.ts, src/pocket/PocketVersionedLambda.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeRuleWithMultipleTargets.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketSQSWithLambdaTarget.spec.ts.snap, src/pocket/__snapshots__/PocketVersionedLambda.spec.ts.snap
- to expose reservedConcurrencyLimit and memorySize (in MB) to lambda props, so that it can be set by the consumping application.
- set to terraform defaults if the concurrency limit or memory size is not set by the consuming application. 
- when not set, reserved concurrency defaults to `-1` (denotes unreserved concurrency)
- when not set, memory size default is 128MB.
terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#reserved_concurrent_executions
Ticket:[ BACK-1417](https://getpocket.atlassian.net/browse/BACK-1417)
=> feat(lambda): expose reservedConcurrencyLimit and memorySize (in MB) to lambda props

src/pocket/PocketECSCodePipeline.spec.ts, src/pocket/PocketECSCodePipeline.ts, src/pocket/__snapshots__/PocketECSCodePipeline.spec.ts.snap
Allow `PocketECSCodePipeline` to be deployed outside of Pocket's AWS account. This currently fails because the artifact bucket is not unique. I ran into this because I'm writing steps on how others can deploy [Pocket/data-flows](https://github.com/Pocket/data-flows).
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/FFRECSV2-218)
- Should we have an organization parameter somewhere, that would allow us to configure the `pocket` string globally?
=> feat(PocketECSCodePipeline): add parameter for custom artifact bucket name [FFRECSV2-218]

src/base/ApplicationVersionedLambda.ts
Allow the use of NodeJS 16 runtime for lambda
Reference: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
=> fix(lambda): add NodeJS 16 support

package-lock.json, package.json
Remove the usage of peer dependencies and require direct usage of explicit versions in our repos.
This will cause these exact versions to always be installed in our repositories. Based on our usage at @pocket I have not seen a use of us using a different version in downstream repos.
=> feat(peer): removing peer depedencies in favor of direct usage

src/pocket/PocketSynthetics.ts, src/pocket/__snapshots__/PocketSynthetics.spec.ts.snap
`sum` went away on June 30th 2022. Updating to use `slideBy` instead. I _think_ this matches the current configuration.
@bassrock mentioned not seeing the conversion code in the UI. That is because they automatically converted it for us.
https://discuss.newrelic.com/t/converting-sum-of-thresholds-to-use-sliding-windows-aggregation/175084
=> fix(newrelic): Update sum to slideBy

src/base/ApplicationEventBridgeRule.spec.ts, src/base/ApplicationEventBridgeRule.ts, src/base/__snapshots__/ApplicationEventBridgeRule.spec.ts.snap, src/pocket/PocketEventBridgeRuleWithMultipleTargets.spec.ts, src/pocket/PocketEventBridgeRuleWithMultipleTargets.ts, src/pocket/__snapshots__/PocketEventBridgeRuleWithMultipleTargets.spec.ts.snap
make passing in a dependent terraform resource optional when creating event bridge rule targets. this change is to satisfy the use case when an event bridge rule target already exists.
* https://getpocket.atlassian.net/browse/BACK-1539
=> fix(EventBridgeRule): make terraform resource optional

src/base/ApplicationSQSQueue.spec.ts, src/base/ApplicationSQSQueue.ts
- set max retention time to 1209600 as per documentation 
doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#message_retention_seconds
build failure - https://us-east-1.console.aws.amazon.com/codesuite/codebuild/996905175585/projects/AccountDataDeleter-PRs-Prod/build/AccountDataDeleter-PRs-Prod%3A9718c345-2bc8-487b-9762-11d483b306dd?region=us-east-1
=> fix: remove validation as its done during terraform apply 

src/pocket/PocketEventBridgeRuleWithMultipleTargets.spec.ts, src/pocket/PocketEventBridgeRuleWithMultipleTargets.ts, src/pocket/PocketEventBridgeWithLambdaTarget.spec.ts, src/pocket/PocketEventBridgeWithLambdaTarget.ts
Expose `scheduleExpression` which was added to `ApplicationEventBridgeRule` through the `Pocket-` constructs, by including the underlying interface for `ApplicationEventBridgeRuleProperties`
* Use the underlying property interface for `ApplicationEventBridgeRule` and allow `Pocket-` class to override portions
=> fix(eventBridgeRule): expose scheduleExpression through Pocket- contructs

src/base/ApplicationSqsSnsTopicSubscription.spec.ts, src/base/ApplicationSqsSnsTopicSubscription.ts, src/base/__snapshots__/ApplicationSqsSnsTopicSubscription.spec.ts.snap
- passing DLQ as an optional parameter to ApplicationSqsSnsTopicSubscriptionProps
- to create DLQ outside this construct and pass them in. then in the consuming application, can set the inline access policy for both the sqs and corresponding dlq for sns subscriptions
- if dlq is passed, use it as dlq for sns
- if dlq is not passed, create one.
=> feat: DLQ as an optional parameter to ApplicationSqsSnsTopicSubscriptionProps

src/base/ApplicationDynamoDBTable.spec.ts, src/base/ApplicationDynamoDBTable.ts, src/base/__snapshots__/ApplicationDynamoDBTable.spec.ts.snap
expose enum of stream types & add error checking when enabling streams.
Tickets:
* https://getpocket.atlassian.net/browse/BACK-1625
=> feat(dynamodb streams): expose enum of stream types & add error checking

src/base/ApplicationEventBridgeRule.ts, src/base/__snapshots__/ApplicationEventBridgeRule.spec.ts.snap, src/pocket/PocketEventBridgeRuleWithMultipleTargets.spec.ts, src/pocket/__snapshots__/PocketEventBridgeRuleWithMultipleTargets.spec.ts.snap, src/pocket/__snapshots__/PocketEventBridgeWithLambdaTarget.spec.ts.snap
expose preventDestroy for event rule
Aws doesnt check if the event-rule has target before it gets deleted.
so we are exposing the `preventDestroy` under lifecycle to help the consuming repo config them
=> chore: expose preventDestroy for event rule

src/base/ApplicationECSService.ts, src/base/__snapshots__/ApplicationECSService.spec.ts.snap, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
Add missing policy action required for ECS tasks running as root writing to EFS filesystems
Tickets:
* https://mozilla-hub.atlassian.net/browse/POC-189
=> fix: missing efs policy action

src/base/ApplicationLoadBalancer.spec.ts, src/base/ApplicationLoadBalancer.ts, src/base/__snapshots__/ApplicationLoadBalancer.spec.ts.snap, src/pocket/PocketALBApplication.ts
In order to do an analysis of access patterns to our ALBs we need to dump the logs to an S3 bucket. From there using a pattern that @jeshuaborges worked on over the holidays we can import the logs to Snowflake for analysis.
This will also let us remove our elasticsearch cluster in favor for some standard data products tooling and SQL much like athena.
* https://pocket.slack.com/archives/C02JZ4TRF0S/p1672269833285189
* https://github.com/Pocket/data-warehouse/pull/91/files
* https://github.com/Pocket/data-warehouse/pull/92
=> feat(accessLogs): adding in access log to s3 support for ALBs

src/pocket/PocketECSApplication.ts
Forgot to pass the provider to the ecs cluster.
=> fix(provider): applying a missing provider

src/base/ApplicationECSAlbCodeDeploy.ts, src/base/ApplicationECSService.ts, src/pocket/PocketALBApplication.ts
Add configurable prop for termination timeout value on successful blue/green deployment - if successful this will speed up the Qdrant deploy which scales it's service to zero prior to deploying so the default 5 minute wait only serves to keep the service unavailable for a needlessly long time. Default value set to 5 minutes, which matches the previous hardcoded value.
Tickets:
* [POC-189](https://mozilla-hub.atlassian.net/browse/POC-189)
=> feat: add prop to configure success termination timeout value

src/pocket/PocketECSCodePipeline.ts, src/pocket/__snapshots__/PocketECSCodePipeline.spec.ts.snap
Adds 'codepipeline' back to identifier, was removed erroneously in v4.8.0
Tickets:
* https://mozilla-hub.atlassian.net/browse/POC-189
=> chore: add 'codepipeline' back to identifier in codepipeline-role

src/pocket/PocketApiGatewayLambdaIntegration.ts, src/pocket/__snapshots__/PocketApiGatewayLambdaIntegration.spec.ts.snap
Trying to fix this error showing up in fxa-webhook-proxy usage:
```
Error: adding Lambda Permission (FxAWebhookProxy-Prod-ApiGateway-FxA-Events-Function/terraform-20230222220002343400000001): InvalidParameterValueException: The provided principal was invalid. Please check the principal and try again.
--
```
Appears that Lambda Permissions require a more specific principal than just `amazonaws.com` - so reverting to `apigateway.amazonaws.com`.
Blocks: successful CI run of https://github.com/Pocket/fxa-webhook-proxy/
=> fix(lambda perm): api gateway lambda permission needs more specific principal

src/base/ApplicationECSContainerDefinition.spec.ts, src/base/ApplicationECSContainerDefinition.ts, src/example.ts
Add additional log parameters for ECS logging. This adds the ability to parse multiline log messages per project, either with timestamps, or regex parsing. Default values match the current setup - both options wouldn't be omitted.
* [Link to docs](https://docs.docker.com/config/containers/logging/awslogs/)
Tickets:
* [POC-217](https://mozilla-hub.atlassian.net/browse/POC-217)
I'll only need the multiline option, adding both options for future flexibility
=> feat(ECSContainer): add datetime and multiline log options to ECS def.

src/pocket/PocketPagerDuty.ts, src/pocket/__snapshots__/PocketPagerDuty.spec.ts.snap
Extends Pagerduty service acknowledgement timeout period from 10 minutes to 30 minutes.
This is only a change to the period of time between the first ack of an alert and when it re-alerts.
=> feat(pagerduty): extend pagerduty svc ack timeout period

src/example.ts, src/pocket/PocketALBApplication.spec.ts, src/pocket/PocketALBApplication.ts, src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
Allow teams to create [wafv2 webacls](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl) in their repository and easily associate them with their PocketALB application.
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl
* https://docs.aws.amazon.com/waf/latest/developerguide/web-acl.html
Associating with a CDN is slightly different, but could be done I think pretty easily. Let me know if we think that is needed I am not sure how many applications use that feature.
=> feat: Allow passing in wafv2webacl and associate it with alb

src/index.ts
Stupidly, I forgot to export the cloudwatch synthetics resources so we could actually use this from this package / module.
=> fix(export): forgot to expore aws synthetics work

src/base/ApplicationVersionedLambda.ts
Update the available runtimes for AWS Lambda in Python and Node
=> chore(lambda): update lambda runtimes

src/base/ApplicationRDSCluster.spec.ts, src/base/ApplicationRDSCluster.ts, src/base/__snapshots__/ApplicationRDSCluster.spec.ts.snap
Allow no name to be passed to RDS so that we can upgrade [Feature Flags](https://github.com/Pocket/feature-flags/pull/385) to latest terraform. Without this terraform tries to replace the database.
=> fix(rds): allowing a no name rds
